name: PR Validation
on:
  pull_request:
    branches:
      - main

jobs:
  pr_check:
    name: Code Check
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Python Setup
        uses: actions/setup-python@v3

      - name: Pre-commit Run
        uses: pre-commit/action@v3.0.0
